# Generated by Django 5.0.5 on 2024-05-09 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('oficina_entrega_nome', models.CharField(max_length=100)),
                ('oficina_entrega_endereco', models.TextField()),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('comentarios_cliente', models.TextField(blank=True, null=True)),
                ('comentarios_fornecedor', models.TextField(blank=True, null=True)),
                ('prazo_entrega', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('itens_orcamento', models.JSONField(default=list)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
