# Generated by Django 5.0.5 on 2024-05-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaPecas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='itens_orcamento',
            field=models.TextField(),
        ),
    ]
