# Generated by Django 5.0.5 on 2024-05-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcaPecas', '0003_orcamento_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamento',
            old_name='cliente',
            new_name='criador',
        ),
    ]
