# Generated by Django 5.0.5 on 2024-06-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaPecas', '0004_rename_cliente_orcamento_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='itens_orcamento',
            field=models.JSONField(default=list),
        ),
    ]
