# Generated by Django 5.0.5 on 2024-06-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaPecas', '0005_alter_orcamento_itens_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='placa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
