# Generated by Django 5.0.5 on 2024-06-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcaPecas', '0006_orcamento_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(default='Pendente', max_length=27),
        ),
    ]
